#app
server:
  port: 8080

spring:
  application:
    name: concurrent-stock

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://39.108.239.82:3306/concurrent-stock
#    username: root
#    password: uAiqwVwjJ8-i
    url: jdbc:mysql://10.128.1.11:3306/concurrent-stock?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false
    username: developer
    password: esoo5X^Xc&nq5^MF


#mybatis
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.cola.concurrentstock.base.model
  # 扫描枚举类 # 支持统配符 * 或者 ; 分割
  type-enums-package: com.cola.concurrentstock.base.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      #column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logback:
  logDir: log/dev
  appName: concurrent-stock
  fileType: log

  #logging
  # 打印mybatis的SQL
logging:
  level:
    com.cola.concurrentstock.base.mapper: INFO
